=== DIDIx13/XML/activite-072-xml-campanule/public_html/campanule.xsd
<?xml version="1.0"?>
<!--
    dominique huguenin (dominique.huguenin@rpn.ch)
-->
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="articles">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="article" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="article" type="typeArticle"/>

    <xs:complexType name="typeArticle">
        <xs:all>
            <xs:element name="identifiant" type="typeIdentifiant" minOccurs="0"/>
            <xs:element name="nom" type="xs:string" minOccurs="0"/>
            <xs:element name="poids" type="xs:decimal" minOccurs="0"/>
            <xs:element name="couleur" type="xs:string" minOccurs="0"/>
            <xs:element name="qteStock" type="xs:integer" minOccurs="0"/>
            <xs:element name="prixAchat" type="xs:decimal" minOccurs="0"/>
            <xs:element name="prixVente" type="xs:decimal" minOccurs="0"/>
            <xs:element name="mouchard" type="typeMouchard" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:element name="clients">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="client" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="client" type="typeClient"/>

    <xs:complexType name="typeClient">
        <xs:all>
            <xs:element name="identifiant" type="typeIdentifiant" minOccurs="0"/>
            <xs:element name="nom" type="xs:string" minOccurs="0"/>
            <xs:element name="prenom" type="xs:string" minOccurs="0"/>
            <xs:element name="localite" type="xs:string" minOccurs="0"/>
            <xs:element name="chiffreAffaire" type="xs:decimal" minOccurs="0"/>
            <xs:element name="typeClient" type="typeClientEnum" minOccurs="0"/>
            <xs:element name="codePays" type="xs:string" minOccurs="0"/>
            <xs:element name="mouchard" type="typeMouchard" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:element name="commandes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="commande" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="commande" type="typeCommande"/>

    <xs:complexType name="typeCommande">
        <xs:all>
            <xs:element name="identifiant" type="typeIdentifiant" minOccurs="0"/>
            <xs:element ref="client" minOccurs="0"/>
            <xs:element name="dateCommande" type="xs:dateTime" minOccurs="0"/>
            <xs:element name="mouchard" type="typeMouchard" minOccurs="0"/>
            <xs:element name="lignes" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="item" type="typeLigne" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="typeLigne">
        <xs:all>
            <xs:element ref="article"/>
            <xs:element name="qteCommandee" type="xs:integer" minOccurs="0"/>
            <xs:element name="prixVenteReel" type="xs:decimal" minOccurs="0"/>
            <xs:element name="qteTotaleLivree" type="xs:integer" minOccurs="0"/>
            <xs:element name="dateLivraisonPrevue" type="xs:dateTime" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="typeIdentifiant">
        <xs:all>
            <xs:element name="uuid" type="xs:string"/>
            <xs:element name="version" type="xs:integer"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="typeMouchard">
        <xs:all>
            <xs:element name="dateCreation" type="xs:dateTime"/>
            <xs:element name="userCreation" type="xs:string"  minOccurs="0"/>
            <xs:element name="dateModification" type="xs:dateTime"  minOccurs="0"/>
            <xs:element name="userModification" type="xs:string"  minOccurs="0"/>
            <xs:element name="dateSuppression" type="xs:dateTime"  minOccurs="0"/>
            <xs:element name="userSuppression" type="xs:string"  minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:simpleType name="typeClientEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="PARTICULIER"/>
            <xs:enumeration value="GRAND_COMPTE"/>
            <xs:enumeration value="ADMINISTRATION"/>
            <xs:enumeration value="PME"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== DIDIx13/XML/activite-072-xml-campanule/public_html/article_DEMO0000-0000-0000-0001-000000000009.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    dominique huguenin (dominique.huguenin@rpn.ch)
-->
<?xml-stylesheet type="text/xsl" href= "campanule.xsl" ?>
<article
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="campanule.xsd">
    <identifiant>
        <uuid>DEMO0000-0000-0000-0001-000000000009</uuid>
        <version>0</version>
    </identifiant>
    <mouchard>
        <dateCreation>2017-11-30T08:19:48.743Z</dateCreation>
        <userCreation>testUser</userCreation>
    </mouchard>
    <nom>PESE-LETTRE1-1000</nom>
    <qteStock>2</qteStock>
    <prixAchat>150.00</prixAchat>
    <prixVente>250.00</prixVente>
</article>

=== DIDIx13/XML/activite-072-xml-campanule/public_html/commande_DEMO0000-0000-0000-0003-000000000004.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    dominique huguenin (dominique.huguenin@rpn.ch)
-->
<?xml-stylesheet type="text/xsl" href= "campanule.xsl" ?>
<commande
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="campanule.xsd">
    <identifiant>
        <uuid>DEMO0000-0000-0000-0003-000000000004</uuid>
        <version>0</version>
    </identifiant>
    <mouchard>
        <dateCreation>2017-11-30T08:19:48.743Z</dateCreation>
        <userCreation>testUser</userCreation>
    </mouchard>
    <client>
        <identifiant>
            <uuid>DEMO0000-0000-0000-0002-000000000001</uuid>
            <version>0</version>
        </identifiant>
        <mouchard>
            <dateCreation>2017-11-30T08:19:48.743Z</dateCreation>
            <userCreation>testUser</userCreation>
        </mouchard>
        <nom>DEFRERE</nom>
        <prenom>Marc</prenom>
        <localite>PARIS</localite>
        <codePays>F</codePays>
        <chiffreAffaire>806.00</chiffreAffaire>
        <typeClient>PARTICULIER</typeClient>
    </client>
    <dateCommande>2010-06-10T00:00:00.000Z</dateCommande>
    <lignes>
        <item>
            <article>
                <identifiant>
                    <uuid>DEMO0000-0000-0000-0001-000000000012</uuid>
                    <version>0</version>
                </identifiant>
                <mouchard>
                    <dateCreation>2017-11-30T08:19:48.743Z</dateCreation>
                    <userCreation>testUser</userCreation>
                </mouchard>
                <nom>CRAYON</nom>
                <poids>20.0</poids>
                <couleur>ROUGE</couleur>
                <qteStock>210</qteStock>
                <prixAchat>1.00</prixAchat>
                <prixVente>2.00</prixVente>
            </article>
            <qteCommandee>1</qteCommandee>
            <qteTotaleLivree>0</qteTotaleLivree>
            <prixVenteReel>5.00</prixVenteReel>
            <dateLivraisonPrevue>2010-06-10T00:00:00.000Z</dateLivraisonPrevue>
        </item>
        <item>
            <article>
                <identifiant>
                    <uuid>DEMO0000-0000-0000-0001-000000000005</uuid>
                    <version>0</version>
                </identifiant>
                <mouchard>
                    <dateCreation>2017-11-30T08:19:48.743Z</dateCreation>
                    <userCreation>testUser</userCreation>
                </mouchard>
                <nom>LAMPE</nom>
                <poids>550.0</poids>
                <couleur>BLANC</couleur>
                <qteStock>3</qteStock>
                <prixAchat>100.00</prixAchat>
                <prixVente>149.00</prixVente>
            </article>
            <qteCommandee>1</qteCommandee>
            <qteTotaleLivree>0</qteTotaleLivree>
            <prixVenteReel>149.00</prixVenteReel>
            <dateLivraisonPrevue>2010-06-10T00:00:00.000Z</dateLivraisonPrevue>
        </item>
        <item>
            <article>
                <identifiant>
                    <uuid>DEMO0000-0000-0000-0001-000000000015</uuid>
                    <version>0</version>
                </identifiant>
                <mouchard>
                    <dateCreation>2017-11-30T08:19:48.743Z</dateCreation>
                    <userCreation>testUser</userCreation>
                </mouchard>
                <nom>CRAYON LUXE</nom>
                <poids>20.0</poids>
                <couleur>VERT</couleur>
                <qteStock>90</qteStock>
                <prixAchat>3.00</prixAchat>
                <prixVente>5.00</prixVente>
            </article>
            <qteCommandee>8</qteCommandee>
            <qteTotaleLivree>0</qteTotaleLivree>
            <prixVenteReel>4.00</prixVenteReel>
            <dateLivraisonPrevue>2010-06-10T00:00:00.000Z</dateLivraisonPrevue>
        </item>
        <item>
            <article>
                <identifiant>
                    <uuid>DEMO0000-0000-0000-0001-000000000002</uuid>
                    <version>0</version>
                </identifiant>
                <mouchard>
                    <dateCreation>2017-11-30T08:19:48.743Z</dateCreation>
                    <userCreation>testUser</userCreation>
                </mouchard>
                <nom>CALCULATRICE</nom>
                <poids>150.0</poids>
                <couleur>NOIR</couleur>
                <qteStock>5</qteStock>
                <prixAchat>200.00</prixAchat>
                <prixVente>235.00</prixVente>
            </article>
            <qteCommandee>2</qteCommandee>
            <qteTotaleLivree>0</qteTotaleLivree>
            <prixVenteReel>235.00</prixVenteReel>
            <dateLivraisonPrevue>2010-06-10T00:00:00.000Z</dateLivraisonPrevue>
        </item>
        <item>
            <article>
                <identifiant>
                    <uuid>DEMO0000-0000-0000-0001-000000000013</uuid>
                    <version>0</version>
                </identifiant>
                <mouchard>
                    <dateCreation>2017-11-30T08:19:48.743Z</dateCreation>
                    <userCreation>testUser</userCreation>
                </mouchard>
                <nom>CRAYON</nom>
                <poids>30.0</poids>
                <couleur>BLEU</couleur>
                <qteStock>190</qteStock>
                <prixAchat>1.00</prixAchat>
                <prixVente>2.00</prixVente>
            </article>
            <qteCommandee>10</qteCommandee>
            <qteTotaleLivree>0</qteTotaleLivree>
            <prixVenteReel>4.00</prixVenteReel>
            <dateLivraisonPrevue>2010-06-10T00:00:00.000Z</dateLivraisonPrevue>
        </item>
    </lignes>
</commande>

=== DIDIx13/XML/activite-072-xml-campanule/public_html/clients.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    dominique huguenin (dominique.huguenin@rpn.ch)
-->
<?xml-stylesheet type="text/xsl" href= "campanule.xsl" ?>
<clients
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="campanule.xsd">
    <client>
        <identifiant>
            <uuid>DEMO0000-0000-0000-0002-000000000001</uuid>
            <version>0</version>
        </identifiant>
        <mouchard>
            <dateCreation>2017-11-30T08:19:48.743Z</dateCreation>
            <userCreation>testUser</userCreation>
        </mouchard>
        <nom>DEFRERE</nom>
        <prenom>Marc</prenom>
        <localite>PARIS</localite>
        <codePays>F</codePays>
        <chiffreAffaire>806.00</chiffreAffaire>
        <typeClient>PARTICULIER</typeClient>
    </client>
    <client>
        <identifiant>
            <uuid>DEMO0000-0000-0000-0002-000000000002</uuid>
            <version>0</version>
        </identifiant>
        <mouchard>
            <dateCreation>2017-11-30T08:19:48.743Z</dateCreation>
            <userCreation>testUser</userCreation>
        </mouchard>
        <nom>DECERF</nom>
        <prenom>Jean</prenom>
        <localite>PARIS</localite>
        <codePays>F</codePays>
        <chiffreAffaire>0.00</chiffreAffaire>
        <typeClient>PARTICULIER</typeClient>
    </client>
    <client>
        <identifiant>
            <uuid>DEMO0000-0000-0000-0002-000000000003</uuid>
            <version>0</version>
        </identifiant>
        <mouchard>
            <dateCreation>2017-11-30T08:19:48.743Z</dateCreation>
            <userCreation>testUser</userCreation>
        </mouchard>
        <nom>DEFAWE</nom>
        <prenom>Leon</prenom>
        <localite>LIEGE</localite>
        <codePays>B</codePays>
        <chiffreAffaire>0.00</chiffreAffaire>
        <typeClient>PARTICULIER</typeClient>
    </client>
    <client>
        <identifiant>
            <uuid>DEMO0000-0000-0000-0002-000000000004</uuid>
            <version>0</version>
        </identifiant>
        <mouchard>
            <dateCreation>2017-11-30T08:19:48.743Z</dateCreation>
            <userCreation>testUser</userCreation>
        </mouchard>
        <nom>NOSSENT</nom>
        <prenom>Serge</prenom>
        <localite>BRUXELLES</localite>
        <codePays>B</codePays>
        <chiffreAffaire>149.00</chiffreAffaire>
        <typeClient>PARTICULIER</typeClient>
    </client>
    <client>
        <identifiant>
            <uuid>DEMO0000-0000-0000-0002-000000000005</uuid>
            <version>0</version>
        </identifiant>
        <mouchard>
            <dateCreation>2017-11-30T08:19:48.743Z</dateCreation>
            <userCreation>testUser</userCreation>
        </mouchard>
        <nom>JACOB</nom>
        <prenom>Marthe</prenom>
        <localite>MARSEILLE</localite>
        <codePays>F</codePays>
        <chiffreAffaire>31.00</chiffreAffaire>
        <typeClient>ADMINISTRATION</typeClient>
    </client>
    <client>
        <identifiant>
            <uuid>DEMO0000-0000-0000-0002-000000000006</uuid>
            <version>0</version>
        </identifiant>
        <mouchard>
            <dateCreation>2017-11-30T08:19:48.743Z</dateCreation>
            <userCreation>testUser</userCreation>
        </mouchard>
        <nom>JAMAR</nom>
        <prenom>Pierre</prenom>
        <localite>LIEGE</localite>
        <codePays>B</codePays>
        <chiffreAffaire>21.00</chiffreAffaire>
        <typeClient>ADMINISTRATION</typeClient>
    </client>
    <client>
        <identifiant>
            <uuid>DEMO0000-0000-0000-0002-000000000007</uuid>
            <version>0</version>
        </identifiant>
        <mouchard>
            <dateCreation>2017-11-30T08:19:48.743Z</dateCreation>
            <userCreation>testUser</userCreation>
        </mouchard>
        <nom>DECKERS</nom>
        <prenom>William</prenom>
        <localite>LYON</localite>
        <codePays>F</codePays>
        <chiffreAffaire>140.00</chiffreAffaire>
        <typeClient>GRAND_COMPTE</typeClient>
    </client>
    <client>
        <identifiant>
            <uuid>DEMO0000-0000-0000-0002-000000000008</uuid>
            <version>0</version>
        </identifiant>
        <mouchard>
            <dateCreation>2017-11-30T08:19:48.743Z</dateCreation>
            <userCreation>testUser</userCreation>
        </mouchard>
        <nom>DECLERCQ</nom>
        <prenom>Lucien</prenom>
        <localite>BRUXELLES</localite>
        <codePays>B</codePays>
        <chiffreAffaire>349.00</chiffreAffaire>
        <typeClient>GRAND_COMPTE</typeClient>
    </client>
    <client>
        <identifiant>
            <uuid>DEMO0000-0000-0000-0002-000000000009</uuid>
            <version>0</version>
        </identifiant>
        <mouchard>
            <dateCreation>2017-11-30T08:19:48.743Z</dateCreation>
            <userCreation>testUser</userCreation>
        </mouchard>
        <nom>DEFYZ</nom>
        <prenom>Maurice</prenom>
        <localite>BORDEAUX</localite>
        <codePays>F</codePays>
        <chiffreAffaire>0.00</chiffreAffaire>
        <typeClient>PARTICULIER</typeClient>
    </client>
    <client>
        <identifiant>
            <uuid>DEMO0000-0000-0000-0002-000000000010</uuid>
            <version>0</version>
        </identifiant>
        <mouchard>
            <dateCreation>2017-11-30T08:19:48.743Z</dateCreation>
            <userCreation>testUser</userCreation>
        </mouchard>
        <nom>DEFOOZ</nom>
        <prenom>Francis</prenom>
        <localite>LILLE</localite>
        <codePays>F</codePays>
        <chiffreAffaire>60.00</chiffreAffaire>
        <typeClient>PARTICULIER</typeClient>
    </client>
    <client>
        <identifiant>
            <uuid>DEMO0000-0000-0000-0002-000000000011</uuid>
            <version>0</version>
        </identifiant>
        <mouchard>
            <dateCreation>2017-11-30T08:19:48.743Z</dateCreation>
            <userCreation>testUser</userCreation>
        </mouchard>
        <nom>RAMJOIE</nom>
        <prenom>Victor</prenom>
        <localite>NANTES</localite>
        <codePays>F</codePays>
        <chiffreAffaire>0.00</chiffreAffaire>
        <typeClient>PARTICULIER</typeClient>
    </client>
    <client>
        <identifiant>
            <uuid>DEMO0000-0000-0000-0002-000000000012</uuid>
            <version>0</version>
        </identifiant>
        <mouchard>
            <dateCreation>2017-11-30T08:19:48.743Z</dateCreation>
            <userCreation>testUser</userCreation>
        </mouchard>
        <nom>RENARDY</nom>
        <prenom>Jean</prenom>
        <localite>MARSEILLE</localite>
        <codePays>F</codePays>
        <chiffreAffaire>275.00</chiffreAffaire>
        <typeClient>GRAND_COMPTE</typeClient>
    </client>
    <client>
        <identifiant>
            <uuid>DEMO0000-0000-0000-0002-000000000013</uuid>
            <version>0</version>
        </identifiant>
        <mouchard>
            <dateCreation>2017-11-30T08:19:48.743Z</dateCreation>
            <userCreation>testUser</userCreation>
        </mouchard>
        <nom>MANTEAU</nom>
        <prenom>Yvan</prenom>
        <localite>PARIS</localite>
        <codePays>F</codePays>
        <chiffreAffaire>320.00</chiffreAffaire>
        <typeClient>GRAND_COMPTE</typeClient>
    </client>
    <client>
        <identifiant>
            <uuid>DEMO0000-0000-0000-0002-000000000014</uuid>
            <version>0</version>
        </identifiant>
        <mouchard>
            <dateCreation>2017-11-30T08:19:48.743Z</dateCreation>
            <userCreation>testUser</userCreation>
        </mouchard>
        <nom>JONAS</nom>
        <prenom>Henri</prenom>
        <localite>PARIS</localite>
        <codePays>F</codePays>
        <chiffreAffaire>0.00</chiffreAffaire>
        <typeClient>PME</typeClient>
    </client>
    <client>
        <identifiant>
            <uuid>DEMO0000-0000-0000-0002-000000000015</uuid>
            <version>0</version>
        </identifiant>
        <mouchard>
            <dateCreation>2017-11-30T08:19:48.743Z</dateCreation>
            <userCreation>testUser</userCreation>
        </mouchard>
        <nom>DELVENNE</nom>
        <prenom>Christian</prenom>
        <localite>LYON</localite>
        <codePays>F</codePays>
        <chiffreAffaire>0.00</chiffreAffaire>
        <typeClient>GRAND_COMPTE</typeClient>
    </client>
    <client>
        <identifiant>
            <uuid>DEMO0000-0000-0000-0002-000000000016</uuid>
            <version>0</version>
        </identifiant>
        <mouchard>
            <dateCreation>2017-11-30T08:19:48.743Z</dateCreation>
            <userCreation>testUser</userCreation>
        </mouchard>
        <nom>DEFEEZ</nom>
        <prenom>Andre</prenom>
        <localite>LYON</localite>
        <codePays>F</codePays>
        <chiffreAffaire>0.00</chiffreAffaire>
        <typeClient>PARTICULIER</typeClient>
    </client>
</clients>

=== DIDIx13/XML/activite-072-xml-campanule/public_html/client_DEMO0000-0000-0000-0002-000000000008.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    dominique huguenin (dominique.huguenin@rpn.ch)
-->
<?xml-stylesheet type="text/xsl" href= "campanule.xsl" ?>
<client 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="campanule.xsd">
    <identifiant>
        <uuid>DEMO0000-0000-0000-0002-000000000008</uuid>
        <version>0</version>
    </identifiant>
    <mouchard>
        <dateCreation>2017-11-30T08:19:48.743Z</dateCreation>
        <userCreation>testUser</userCreation>
    </mouchard>
    <nom>DECLERCQ</nom>
    <prenom>Lucien</prenom>
    <localite>BRUXELLES</localite>
    <codePays>B</codePays>
    <chiffreAffaire>349.00</chiffreAffaire>
    <typeClient>GRAND_COMPTE</typeClient>
</client>
