=== DIDIx13/XML/activite-071-xml-contact/public_html/contacts.xsd
<?xml version="1.0"?>
<!--
    dominique huguenin (dominique.huguenin@rpn.ch)
-->
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="contacts">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="contact" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="contact" type="typeContact"/>

    <xs:complexType name="typeContact">
        <xs:all>
            <xs:element name="identifiant" type="typeIdentifiant" minOccurs="0"/>
            <xs:element name="nom" type="xs:string" minOccurs="0"/>
            <xs:element name="date-naissance" type="xs:dateTime" minOccurs="0"/>
            <xs:element name="telephones">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="telephone" type="typeTelephone"
                                    minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="adresses">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="adresse" type="typeAdresse"
                                    minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="typeTelephone">
        <xs:all>
            <xs:element name="numRef" type="xs:integer"/>
            <xs:element name="categorie" type="typeCategorie"/>
            <xs:element name="numero" type="xs:string"/>
        </xs:all>
    </xs:complexType>
    
    <xs:complexType name="typeAdresse">
        <xs:all>
            <xs:element name="numRef" type="xs:integer"/>
            <xs:element name="rue" type="xs:string"/>
            <xs:element name="localite" type="xs:string"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="typeIdentifiant">
        <xs:all>
            <xs:element name="UUID" type="xs:string"/>
        </xs:all>
    </xs:complexType>
    
    <xs:simpleType name="typeCategorie">
        <xs:restriction base="xs:string">
            <xs:enumeration value="PRIVE"/>
            <xs:enumeration value="PROFESSIONNEL"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== DIDIx13/XML/activite-071-xml-contact/public_html/contact_12345678-1234-1234-1234-123456789012.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    dominique huguenin (dominique.huguenin@rpn.ch)
-->
<?xml-stylesheet type="text/xsl" href= "contacts.xsl" ?>
<contact
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="contacts.xsd">
    <identifiant>
        <UUID>12345678-1234-1234-1234-123456789012</UUID>
    </identifiant>
    <nom>pier</nom>
    <date-naissance>1990-11-29T00:00:00</date-naissance>
    <telephones>
        <telephone>
            <numRef>1</numRef>
            <categorie>PRIVE</categorie>
            <numero>+41 32 123 45 67</numero>
        </telephone>
        <telephone>
            <numRef>2</numRef>
            <categorie>PROFESSIONNEL</categorie>
            <numero>+41 12 345 67 89</numero>
        </telephone>
    </telephones>
    <adresses>
        <adresse>
            <numRef>1</numRef>
            <rue>rue de pier 1</rue>
            <localite>ville 1 de pier</localite>
        </adresse>
        <adresse>
            <numRef>2</numRef>
            <rue>rue de pier 2</rue>
            <localite>ville 2 de pier</localite>
        </adresse>
    </adresses>    
    
</contact>

=== DIDIx13/XML/activite-071-xml-contact/public_html/contacts.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    dominique huguenin (dominique.huguenin@rpn.ch)
-->
<?xml-stylesheet type="text/xsl" href= "contacts.xsl" ?>
<contacts
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="contacts.xsd">
    <contact>
        <identifiant>
            <UUID>12345678-1234-1234-1234-123456789012</UUID>
        </identifiant>
        <nom>pier</nom>
        <date-naissance>1990-11-29T00:00:00</date-naissance>
        <telephones>
            <telephone>
                <numRef>1</numRef>
                <categorie>PRIVE</categorie>
                <numero>+41 32 123 45 67</numero>
            </telephone>
            <telephone>
                <numRef>2</numRef>
                <categorie>PROFESSIONNEL</categorie>
                <numero>+41 12 345 67 89</numero>
            </telephone>
        </telephones>
        <adresses>
            <adresse>
                <numRef>1</numRef>
                <rue>rue de pier 1</rue>
                <localite>ville 1 de pier</localite>
            </adresse>
            <adresse>
                <numRef>2</numRef>
                <rue>rue de pier 2</rue>
                <localite>ville 2 de pier</localite>
            </adresse>
        </adresses>    
    </contact>
    <contact>
        <identifiant>
            <UUID>12345678-1234-1234-1234-123456789012</UUID>
        </identifiant>
        <nom>pol</nom>
        <telephones>
            <telephone>
                <numRef>1</numRef>
                <categorie>PRIVE</categorie>
                <numero>+41 12 345 67 89</numero>
            </telephone>
        </telephones>
        <adresses>
            <adresse>
                <numRef>1</numRef>
                <rue>rue de pol 1</rue>
                <localite>ville 1 de pol</localite>
            </adresse>
        </adresses>    
    </contact>
    <contact>
        <identifiant>
            <UUID>12345678-1234-1234-1234-123456789012</UUID>
        </identifiant>
        <nom>jak</nom>
        <date-naissance>1990-11-29T00:00:00</date-naissance>
        <telephones/>
        <adresses/>
    </contact>
    <contact>
        <telephones/>
        <adresses/>
    </contact>
</contacts>
